#!/bin/bash

echo "Installing configuration files..."
cp configs/general.config.js configs/general.js
cp configs/reactor.config.js configs/reactor.js

echo "Installing bower packages..."
bower install

echo "Installing npm packages..."
npm install
