#!/bin/bash
echo "Installing configuration files..."
if [ ! -e "configs/general.js" ]; then
    cp configs/general.config.js configs/general.js
fi
if [ ! -e "configs/server.js" ]; then
    cp configs/server.config.js configs/server.js
fi
if [ ! -e "configs/reactor.js" ]; then
    cp configs/reactor.config.js configs/reactor.js
fi
if [ ! -e "configs/facets.js" ]; then
    cp configs/facets.config.js configs/facets.js
fi
if [ ! -e "plugins/email/config.js" ]; then
    cp plugins/email/config.sample.js plugins/email/config.js
fi
echo "Installing bower packages..."
bower install

echo "Installing npm packages..."
npm install
